M48
; DRILL file {KiCad 8.0.1} date 2024-05-25T23:28:13+0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-05-25T23:28:13+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.500
%
G90
G05
T1
X107.36Y-80.205
X113.14Y-80.205
T2
X84.45Y-101.3
X98.4Y-150.1
X136.05Y-101.3
X142.7Y-144.6
M30
